### PR TITLE
Add ASP.NET MVC channel

### PR DESCRIPTION
**Pull request by lAnubisl**

### CODE REVIEW

**Comment by lAnubisl** [comment]
Why is it Invalid?

**Comment by andrew--r** [comment]
Because there is only one uploaded video on that channel.

**Comment by lAnubisl** [comment]
Look at playlists

**Comment by andrew--r** [comment]
I add channel to this list only if this channel contains high quality original content, uploaded by channel's owner.

**Comment by lAnubisl** [comment]
Ok. I will re-upload my videos to that channel

**Pull request closed without merging**
